scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    totp:
        enabled: true
        issuer: 'ProjetLamaZoo'
        server_name: 'ProjetLamaZoo'
        template: security/2fa_check.html.twig
