security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Personnel
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppCustomAuthenticator
            logout:
                path: app_logout
            two_factor:
                auth_form_path: /2fa         # route du formulaire 2FA générée par le bundle
                check_path: /2fa_check       # route de vérification générée par le bundle
                post_only: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/private, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/manual-2fa-check, roles: IS_AUTHENTICATED_FULLY }




