# Charge toutes les routes de tes contrôleurs (avec attributs)
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Routes nécessaires pour SchebTwoFactorBundle
2fa_login:
    path: /2fa
    defaults:
        _controller: scheb_two_factor.form_controller:form

2fa_login_check:
    path: /2fa_check
